### Churn Modelling

#### Importing required libraries

In [3]:
import numpy as np
import pandas as pd
import tensorflow as tf

### Dataset loading

In [4]:
data=pd.read_csv("Churn_Modelling.csv")
data.head()

RowNumber  CustomerId   Surname  CreditScore Geography  Gender  Age  \
0          1    15634602  Hargrave          619    France  Female   42   
1          2    15647311      Hill          608     Spain  Female   41   
2          3    15619304      Onio          502    France  Female   42   
3          4    15701354      Boni          699    France  Female   39   
4          5    15737888  Mitchell          850     Spain  Female   43   

   Tenure    Balance  NumOfProducts  HasCrCard  IsActiveMember  \
0       2       0.00              1          1               1   
1       1   83807.86              1          0               1   
2       8  159660.80              3          1               0   
3       1       0.00              2          0               0   
4       2  125510.82              1          1               1   

   EstimatedSalary  Exited  
0        101348.88       1  
1        112542.58       0  
2        113931.57       1  
3         93826.63       0  
4         79084.10       0

In [5]:
data.describe()

RowNumber    CustomerId   CreditScore           Age        Tenure  \
count  10000.00000  1.000000e+04  10000.000000  10000.000000  10000.000000   
mean    5000.50000  1.569094e+07    650.528800     38.921800      5.012800   
std     2886.89568  7.193619e+04     96.653299     10.487806      2.892174   
min        1.00000  1.556570e+07    350.000000     18.000000      0.000000   
25%     2500.75000  1.562853e+07    584.000000     32.000000      3.000000   
50%     5000.50000  1.569074e+07    652.000000     37.000000      5.000000   
75%     7500.25000  1.575323e+07    718.000000     44.000000      7.000000   
max    10000.00000  1.581569e+07    850.000000     92.000000     10.000000   

             Balance  NumOfProducts    HasCrCard  IsActiveMember  \
count   10000.000000   10000.000000  10000.00000    10000.000000   
mean    76485.889288       1.530200      0.70550        0.515100   
std     62397.405202       0.581654      0.45584        0.499797   
min         0.000000       1.000000      0.00000        0.000000   
25%         0.000000       1.000000      0.00000        0.000000   
50%     97198.540000       1.000000      1.00000        1.000000   
75%    127644.240000       2.000000      1.00000        1.000000   
max    250898.090000       4.000000      1.00000        1.000000   

       EstimatedSalary        Exited  
count     10000.000000  10000.000000  
mean     100090.239881      0.203700  
std       57510.492818      0.402769  
min          11.580000      0.000000  
25%       51002.110000      0.000000  
50%      100193.915000      0.000000  
75%      149388.247500      0.000000  
max      199992.480000      1.000000

### Declaring dependent and independent variables

In [6]:
x=data.iloc[:, 3:-1].values
y=data.iloc[:, -1].values

In [7]:
x

array([[619, 'France', 'Female', ..., 1, 1, 101348.88],
       [608, 'Spain', 'Female', ..., 0, 1, 112542.58],
       [502, 'France', 'Female', ..., 1, 0, 113931.57],
       ...,
       [709, 'France', 'Female', ..., 0, 1, 42085.58],
       [772, 'Germany', 'Male', ..., 1, 0, 92888.52],
       [792, 'France', 'Female', ..., 1, 0, 38190.78]], dtype=object)

In [8]:
y

array([1, 0, 1, ..., 1, 1, 0], dtype=int64)

### Encoding the required fields/attributes of dependent dataset

In [9]:
from sklearn.preprocessing import LabelEncoder
le=LabelEncoder()
x[:,2]=le.fit_transform(x[:, 2])
x

array([[619, 'France', 0, ..., 1, 1, 101348.88],
       [608, 'Spain', 0, ..., 0, 1, 112542.58],
       [502, 'France', 0, ..., 1, 0, 113931.57],
       ...,
       [709, 'France', 0, ..., 0, 1, 42085.58],
       [772, 'Germany', 1, ..., 1, 0, 92888.52],
       [792, 'France', 0, ..., 1, 0, 38190.78]], dtype=object)

In [10]:
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder
ct=ColumnTransformer(transformers=[('encoder', OneHotEncoder(), [1])], remainder='passthrough')
x = np.array(ct.fit_transform(x))

### Splitting dataset into training and testing sets

In [11]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(x, y, test_size = 0.2, random_state = 42)

### Feature Scaling the dataset

In [12]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)

### Building the ANN

### Initialising the ANN

In [13]:
ann = tf.keras.models.Sequential()

### Adding input layer

In [14]:
ann.add(tf.keras.layers.Dense(units=6, activation='relu'))

### Adding hidden layer 1

In [15]:
ann.add(tf.keras.layers.Dense(units=6, activation='relu'))

### Adding output layer
#### (Here node count is 1 for the output of binary classification)

In [16]:
ann.add(tf.keras.layers.Dense(units=1, activation='sigmoid'))

### Training the ANN

### Compiling the ANN

In [17]:
ann.compile(optimizer = 'adam', loss = 'binary_crossentropy', metrics = ['accuracy'])

### Training the ANN

In [18]:
ann.fit(X_train, y_train, batch_size = 100, epochs = 100)

Epoch 1/100
80/80 [==============================] - 1s 4ms/step - loss: 0.7095 - accuracy: 0.6140
Epoch 2/100
80/80 [==============================] - 0s 4ms/step - loss: 0.5493 - accuracy: 0.7448
Epoch 3/100
80/80 [==============================] - 0s 3ms/step - loss: 0.4925 - accuracy: 0.7835
Epoch 4/100
80/80 [==============================] - 0s 3ms/step - loss: 0.4671 - accuracy: 0.7961
Epoch 5/100
80/80 [==============================] - 0s 3ms/step - loss: 0.4545 - accuracy: 0.7991
Epoch 6/100
80/80 [==============================] - 0s 3ms/step - loss: 0.4463 - accuracy: 0.8044
Epoch 7/100
80/80 [==============================] - 0s 3ms/step - loss: 0.4399 - accuracy: 0.8066
Epoch 8/100
80/80 [==============================] - 0s 3ms/step - loss: 0.4345 - accuracy: 0.8124
Epoch 9/100
80/80 [==============================] - 0s 3ms/step - loss: 0.4299 - accuracy: 0.8176
Epoch 10/100
80/80 [==============================] - 0s 3ms/step - loss: 0.4254 - accuracy: 0.8181
Epoch 11/

80/80 [==============================] - 0s 3ms/step - loss: 0.3379 - accuracy: 0.8605
Epoch 84/100
80/80 [==============================] - 0s 3ms/step - loss: 0.3373 - accuracy: 0.8606
Epoch 85/100
80/80 [==============================] - 0s 3ms/step - loss: 0.3372 - accuracy: 0.8621
Epoch 86/100
80/80 [==============================] - 0s 3ms/step - loss: 0.3370 - accuracy: 0.8618
Epoch 87/100
80/80 [==============================] - 0s 3ms/step - loss: 0.3374 - accuracy: 0.8591
Epoch 88/100
80/80 [==============================] - 0s 3ms/step - loss: 0.3368 - accuracy: 0.8608
Epoch 89/100
80/80 [==============================] - 0s 4ms/step - loss: 0.3366 - accuracy: 0.8606
Epoch 90/100
80/80 [==============================] - 0s 3ms/step - loss: 0.3359 - accuracy: 0.8620
Epoch 91/100
80/80 [==============================] - 0s 3ms/step - loss: 0.3364 - accuracy: 0.8625
Epoch 92/100
80/80 [==============================] - 0s 3ms/step - loss: 0.3356 - accuracy: 0.8618
Epoch 93/100


### Making the prediction and evaluating the model

In [19]:
y_pred = ann.predict(X_test)
y_pred = (y_pred > 0.5)
print(np.concatenate((y_pred.reshape(len(y_pred),1), y_test.reshape(len(y_test),1)),1))

63/63 [==============================] - 0s 3ms/step
[[0 0]
 [0 0]
 [0 0]
 ...
 [1 1]
 [0 1]
 [0 1]]


In [20]:
from sklearn.metrics import confusion_matrix, accuracy_score
cm = confusion_matrix(y_test, y_pred)
print(cm)
accuracy_score(y_test, y_pred)

[[1529   78]
 [ 197  196]]


0.8625

### - Work done by Manish Kumar(20SCSE1010830)